plugins {
    id 'idea'
    id 'java'
    id 'jacoco'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.lombok)
    alias(libs.plugins.sonarqube)
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.get())
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.spring.boot.starter.actuator
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.data.redis
    implementation libs.spring.boot.starter.mail
    implementation libs.spring.boot.starter.oauth2.client
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.web
    implementation libs.spring.retry

    implementation libs.ulid.creator
    implementation libs.jackson.datatype.jsr310
    implementation libs.jackson.databind
    implementation libs.springdoc.openapi.starter.webmvc.ui
    implementation libs.p6spy.spring.boot.starter
    implementation libs.apache.httpclient

    implementation libs.querydsl.jpa, { artifact { classifier = 'jakarta' } }
    annotationProcessor libs.querydsl.apt, { artifact { classifier = 'jakarta' } }
    annotationProcessor libs.jakarta.annotation.api
    annotationProcessor libs.jakarta.persistence.api

    implementation libs.bundles.jjwt
    implementation libs.bundles.redisson

    developmentOnly libs.spring.boot.devtools
    developmentOnly libs.spring.boot.docker.compose
    runtimeOnly libs.mysql.connector.j
    annotationProcessor libs.spring.boot.configuration.processor

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.security.test
    testRuntimeOnly libs.h2
    testRuntimeOnly libs.junit.platform.launcher
    testImplementation libs.datafaker
    testImplementation libs.embedded.redis

    testImplementation libs.bundles.autoparams
    testImplementation libs.bundles.fixture.monkey
    testImplementation libs.bundles.jqwik
    testImplementation libs.bundles.testcontainers
}

test {
    useJUnitPlatform {
        def includeTagsProp = project.findProperty("includeTags")
        def excludeTagsProp = project.findProperty("excludeTags")

        if (includeTagsProp) includeTags includeTags.toString().split(',').collect { it.trim() } as String[]
        if (excludeTagsProp) excludeTags includeTags.toString().split(',').collect { it.trim() } as String[]
    }
    systemProperty 'user.timezone', 'Asia/Seoul'
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = 'app.jar'
}

jacoco {
    toolVersion = libs.versions.jacoco.get()
}

jacocoTestReport {
    dependsOn test

    reports {
        html.required = true
        xml.required = true
        csv.required = false
    }

    def Qdomains = []
    for (qPattern in "**/QA".."**/QZ") Qdomains.add(qPattern + "*")

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, excludes: [
                    "**/*Application*",
                    "**/config/**",
                    "**/*Dto*",
                    "**/*Request*",
                    "**/*Response*",
                    "**/dto/**",
                    "**/*Interceptor*",
                    "**/*Exception*",
                    "**/*Properties*",
                    "**/model/**"
            ] + Qdomains)
        }))
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    violationRules {
        rule {
            enabled = true
            element = 'CLASS'

            excludes = [
                    "**.*Application*",
                    "**/config/**",
                    "**.*Dto*",
                    "**.*Request*",
                    "**.*Response*",
                    "**/dto/**",
                    "**.*Exception*",
                    "**.*Properties*",
                    "**/Q*",
                    "**/model/**"
            ]

            limit {
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 0.00
            }

            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.00
            }
        }
    }
}

sonar {
    properties {
        property 'sonar.projectKey', ''
        property 'sonar.host.url', ''
        property 'sonar.token', ''
        property 'sonar.sourceEncoding', 'UTF-8'
        property 'sonar.coverage.jacoco.xmlReportPaths', 'build/reports/jacoco/test/jacocoTestReport.xml'
        def coverageExclusions = [
                '**/*Application.java',
                '**/config/**',
                '**/*Dto.java',
                '**/*Request.java',
                '**/*Response.java',
                '**/dto/**',
                '**/*Interceptor.java',
                '**/*Exception.java',
                '**/*Properties.java',
                '**/Q*.java',
                '**/model/**'
        ]
        property 'sonar.coverage.exclusions', coverageExclusions.join(',')
    }
}
