name: demo-docker

services:

  mysql:
    image: "groonga/mroonga:mysql-8.0.44-15.21"
    container_name: "demo-mysql"
    restart: "unless-stopped"
    networks: [ "demo-network" ]
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "TZ=Asia/Seoul"
    ports: [ "${DB_HOST_PORT}:${DB_CONTAINER_PORT}" ]
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/log:/var/log/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  valkey:
    image: "valkey/valkey:7.2.11-alpine"
    container_name: "demo-valkey"
    restart: "unless-stopped"
    networks: [ "demo-network" ]
    environment: [ "TZ=Asia/Seoul" ]
    ports: [ "${VALKEY_HOST_PORT}:${VALKEY_CONTAINER_PORT}" ]
    volumes: [ "valkey-data:/data" ]
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  dbgate:
    image: "dbgate/dbgate:6.8.2-alpine"
    container_name: "demo-dbgate"
    restart: "unless-stopped"
    networks: [ "demo-network" ]
    ports: [ "${DBGATE_HOST_PORT}:${DBGATE_CONTAINER_PORT}" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:2.13.5"
    container_name: "demo-nginx-proxy-manager"
    restart: "unless-stopped"
    networks: [ "demo-network" ]
    environment: [ "TZ=Asia/Seoul" ]
    ports:
      - "${NPM_HTTP_HOST_PORT}:${NPM_HTTP_CONTAINER_PORT}"
      - "${NPM_HTTPS_HOST_PORT}:${NPM_HTTPS_CONTAINER_PORT}"
      - "${NPM_ADMIN_HOST_PORT}:${NPM_ADMIN_CONTAINER_PORT}"
    volumes:
      - "npm-data:/data"
      - "npm-letsencrypt:/etc/letsencrypt"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  postgresql:
    profiles: [ "dev" ]
    image: "groonga/pgroonga:4.0.5-alpine-14"
    container_name: "demo-dev-postgresql"
    restart: "unless-stopped"
    networks: [ "demo-dev-network" ]
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "TZ=Asia/Seoul"
    ports: [ "5432:5432" ]
    volumes: [ "postgresql-data:/var/lib/postgresql/data" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  smtp4dev:
    profiles: [ "dev" ]
    image: "rnwood/smtp4dev:latest"
    container_name: "demo-dev-smtp4dev"
    restart: "unless-stopped"
    networks: [ "demo-dev-network" ]
    ports: [ "5000:80", "2525:25" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  init-sonarqube:
    profiles: [ "dev" ]
    image: "busybox:1.36.1"
    container_name: "init-demo-dev-sonarqube"
    user: "root"
    command: chown -R 1000:1000 /opt/sonarqube/data /opt/sonarqube/extensions /opt/sonarqube/logs
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "./docker/sonarqube/logs:/opt/sonarqube/logs"

  sonarqube:
    profiles: [ "dev" ]
    image: "sonarqube:25.12.0.117093-community"
    container_name: "demo-dev-sonarqube"
    restart: "unless-stopped"
    depends_on:
      postgresql:
        condition: "service_started"
      init-sonarqube:
        condition: "service_completed_successfully"
    networks: [ "demo-dev-network" ]
    environment:
      - "SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}"
      - "SONAR_JDBC_USERNAME=${POSTGRES_USER}"
      - "SONAR_JDBC_PASSWORD=${POSTGRES_PASSWORD}"
      - "SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true"
      - "TZ=Asia/Seoul"
    ports: [ "9000:9000" ]
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "./docker/sonarqube/logs:/opt/sonarqube/logs"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

volumes:
  mysql-data:
    driver: local
  valkey-data:
    driver: local
  npm-data:
    driver: local
  npm-letsencrypt:
    driver: local
  postgresql-data:
    driver: local
  sonarqube-data:
    driver: local
  sonarqube-extensions:
    driver: local

networks:
  demo-network:
    driver: bridge
  demo-dev-network:
    driver: bridge