SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE accounts;
TRUNCATE TABLE oauth_connections;
TRUNCATE TABLE performances;
TRUNCATE TABLE seats;
TRUNCATE TABLE reservations;
TRUNCATE TABLE payments;

SET REFERENTIAL_INTEGRITY TRUE;