name: Docker

on:
  workflow_dispatch:
    inputs:
      no_cache:
        description: '🧹 기존 캐시를 무시하고 새로 빌드하시겠습니까?'
        required: false
        default: false
        type: boolean
  push:
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '**/docker-compose.override.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '**/docker-compose.override.yml'
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  EXTERNAL_IMAGES: "groonga/mroonga:mysql-8.0.44-15.21 valkey/valkey:7.2.11-alpine"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull & Cache External Images
        if: env.EXTERNAL_IMAGES != ''
        run: |
          for img in $EXTERNAL_IMAGES; do
            docker pull $img
          done

      - name: Build Local Dockerfiles
        run: |
          CACHE_OPTION=""
          if [ "${{ inputs.no_cache }}" == "true" ]; then
            CACHE_OPTION="--no-cache"
          fi
          
          find . -name "Dockerfile" -not -path "*/.*" | while read dockerfile; do
            dir=$(dirname "$dockerfile")
            module_name=$(basename "$dir")

            if [ "$module_name" == "." ] then
              raw_image_name="${{ github.repository }}"
              cache_scope="root
            else
              raw_image_name="${{ github.repository }}/$module_name"
              cache_scope="$module_name"
            fi

            image_tag=$(echo "$raw_image_name" | tr '[:upper:]' '[:lower:]'):latest

            docker buildx build \
              $CACHE_OPTION \
              --tag "$image_tag" \
              --file "$dockerfile" \
              --cache-from type=gha,scope=$cache_scope \
              --cache-to type=gha,mode=max,scope=$cache_scope \
              --load \
              "$dir"
          done

      - name: Start Containers with Compose
        run: |
          find . -name "docker-compose.yml" -not -path "*/.*" | while read compose_file; do
            dir=$(dirname "$compose_file")
            (
              cd "$dir"
              docker compose up -d
            )
          done